### ISSUE TITLE
Error CORS in the site (sometimes)

### ISSUE THREAD

**Issue by dippas** [Filnor/RankOverflow#13]
Getting CORS error whenever I enter the site:

>  Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css. (Reason: CORS request did not succeed).

**Comment by Filnor** [comment]
I can't reproduce this error currently. However, I'll still update the resources with some patches for the scoreboard.
