### ISSUE TITLE
Loading won't finish

### ISSUE THREAD

**Issue by Filnor** [Filnor/RankOverflow#2]
Reported by [dippas in SOBotics](https://chat.stackoverflow.com/transcript/message/41904776#41904776). After putting in an user profile URL and clicking on the button to calculate, the loader never dissappears.

**Comment by dippas** [comment]
@pbdevch  I'm subscribed to this issue, interested in to know what is the bug?

**Comment by Filnor** [comment]
@dippas Not quite sure yet, but I assume my code got borked due to a style or script change on the side of SO/SE. I also considered to switch the current to code to Python (which *should* make the reading out the required data from the site much easier), but that's pretty low on my list right now.
